import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import bgSidebarMobile from "../../public/images/bg-sidebar-mobile.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen min-h-screen text-gray-900 flex flex-col items-center justify-center bg-[#bfe2fd]`}
      >
        <div className="absolute inset-0 h-44 -z-10">
          <Image
            src={bgSidebarMobile}
            alt="Background mobile"
            fill
            className="object-cover"
          />
        </div>
        {children}
      </body>
    </html>
  );
}
